### ISSUE TITLE
Add a Pro Feature flag to documentation 

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/semperpluginstheme#52] opened 2016-08-31 19:51 UTC
On any documentation for a Pro only feature, add a Pro Feature Only message with a link to upgrade.

**Comment by michaeltorbert** [comment] 2016-08-31 19:54
I'm closing this as a duplicate of https://github.com/semperfiwebdesign/semperpluginstore/issues/192

**Closed by michaeltorbert** 2016-08-31 19:54 UTC
