### ISSUE TITLE
check h1, h2 tags for every type of page

### ISSUE THREAD

**Issue by michaeltorbert** [semperfiwebdesign/semperpluginstheme#15] opened 2016-05-10 19:40 UTC
Home page, product pages, posts, pages, etc. Make sure we're using header tags correctly

**Comment by wpsmort** [comment] 2016-05-26 16:50
This is now done with the exception of the main Support page which is missing the H1 page title because of a confirmed bug in Simple:Press. Andy at Simple:Press said they are working on fixing this.

**Comment by wpsmort** [comment] 2017-05-24 22:37
This is now fixed for the Support page as well.

**Closed by wpsmort** 2017-05-24 22:37 UTC
